# Generated by Django 3.2.13 on 2022-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_of_dish', models.CharField(choices=[('A', 'Appetizer'), ('MD', 'Main dishe'), ('B', 'Bar')], default='MD', max_length=2)),
            ],
        ),
    ]
