# Generated by Django 3.2.13 on 2022-05-04 18:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.menu_image_file_path),
        ),
    ]
