# Generated by Django 3.2.13 on 2022-05-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='type_of_dish',
            field=models.CharField(choices=[('A', 'Appetizer'), ('MD', 'Main dish'), ('B', 'Bar')], default='MD', max_length=2),
        ),
    ]
