# Generated by Django 3.2.13 on 2022-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
